"""add password_change_token and pending_password to users

Revision ID: 1a716309c4d0
Revises: 71207e13ecac
Create Date: 2026-02-23 20:54:26.853859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a716309c4d0'
down_revision = '71207e13ecac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('default_lot_size', sa.Float(), nullable=False),
    sa.Column('default_stop_loss', sa.Integer(), nullable=False),
    sa.Column('default_take_profit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_change_token', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('pending_password', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['password_change_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pending_password')
        batch_op.drop_column('password_change_token')

    op.drop_table('user_strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###
