"""prop_firm_rules_and_strategy_wallet

Revision ID: 278da88e353b
Revises: 8961a97d7c0c
Create Date: 2026-03-17 15:12:46.971365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278da88e353b'
down_revision = '8961a97d7c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metaapi_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_prop_firm', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('prop_initial_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prop_daily_loss_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prop_profit_target_pct', sa.Float(), nullable=True))

    with op.batch_alter_table('user_strategies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'metaapi_accounts', ['wallet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_strategies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('wallet_id')

    with op.batch_alter_table('metaapi_accounts', schema=None) as batch_op:
        batch_op.drop_column('prop_profit_target_pct')
        batch_op.drop_column('prop_daily_loss_pct')
        batch_op.drop_column('prop_initial_balance')
        batch_op.drop_column('is_prop_firm')

    # ### end Alembic commands ###
