"""remove pending_password from users

Revision ID: 6550a060bd32
Revises: 1a716309c4d0
Create Date: 2026-02-25 12:13:53.766433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6550a060bd32'
down_revision = '1a716309c4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pending_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_password', sa.VARCHAR(length=256), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
