"""add_prop_phase_and_dollar_limits

Revision ID: 6ecc2147096f
Revises: 278da88e353b
Create Date: 2026-03-17 15:21:08.755648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecc2147096f'
down_revision = '278da88e353b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metaapi_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prop_phase', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('prop_max_loss_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prop_profit_target_usd', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metaapi_accounts', schema=None) as batch_op:
        batch_op.drop_column('prop_profit_target_usd')
        batch_op.drop_column('prop_max_loss_usd')
        batch_op.drop_column('prop_phase')

    # ### end Alembic commands ###
